### ISSUE TITLE
Getting error replicating your samples.

### ISSUE THREAD

**Issue by RedEyedDog** [meddbase/isotope80#10]
Hi,

Im just testing this repo out.. went to setup and project similar to your console sample and im getting this error:

`'Query' is an ambiguous reference between 'Isotope80.Query' and 'LanguageExt.Query' [isotop80Test]csharp(CS0104)`

Thanks

**Comment by colethecoder** [comment]
This is an unfortunate naming clash between the two libraries that I intend to fix at some point. For now if you add:

```
using Query = Isotope80.Query;
```

at the top of your file it should work.

**Comment by RedEyedDog** [comment]
Thanks. I was thinking that but couldn't understand how you made it work lol
