### ISSUE TITLE
Breaking Change: Query renamed to Select

### ISSUE THREAD

**Issue by colethecoder** [meddbase/isotope80#14]
As seen in issue #10 since this project started LanguageExt added it's own Query type. Isotope is intended to be used alongside LanguageExt so the clash of types with the same name is awkward. There are obviously workarounds but it's just awkwardness and noise that is unnecessary so we have made the decision to rename `Query` to `Select`. Hopefully this is a relatively mechanical change for anyone using the project but I apologise for the inconvenience, I think it's worth it in the long run.

**Comment by louthy** [comment]
*ahem*  `Query` has been in language-ext since before this project existed ;)
